"""Add profile_image to users

Revision ID: 7b458b68d105
Revises: bc47fb228408
Create Date: 2026-01-20 23:52:16.164951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7b458b68d105'
down_revision: Union[str, None] = 'bc47fb228408'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_image', sa.String(length=500), nullable=True))
    op.drop_column('users', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', mysql.ENUM('BUYER', 'SELLER', 'ADMIN', collation='utf8mb4_unicode_ci'), nullable=False))
    op.drop_column('users', 'profile_image')
    # ### end Alembic commands ###
